# Generated by Django 3.0.8 on 2020-11-03 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_coach',
            fields=[
                ('coach_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('coach_category', models.CharField(blank=True, max_length=100, null=True)),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_mail', models.EmailField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coach_url', models.FileField(upload_to='media/')),
                ('coach_min_cost', models.IntegerField(default=0)),
                ('coach_max_cost', models.IntegerField(default=0)),
            ],
        ),
    ]
