# Generated by Django 3.0.8 on 2020-11-03 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_cust',
            fields=[
                ('cust_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_mail', models.EmailField(max_length=100, unique=True)),
                ('cust_phone', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cust_url', models.FileField(upload_to='media/')),
            ],
        ),
    ]
