# Generated by Django 3.0.8 on 2020-11-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201104_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_cust',
            name='cust_url',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
